force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/opportunity_name__c.field-meta.xml
<CustomField>
    <fullName>opportunity_name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>opportunity name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/parent_policy__c.field-meta.xml
<CustomField>
    <fullName>parent_policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>parent policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/policy_number__c.field-meta.xml
<CustomField>
    <fullName>policy_number__c</fullName>
    <label>policy number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Renew_Policy__c.field-meta.xml
<CustomField>
    <fullName>Renew_Policy__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Renew Policy</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PolicyTrigger.cls
public class PolicyTrigger {
    public static void policyTrig(list<Policy__c> polList){
        if(polList!=null && !polList.isEmpty()){
        try{
           
            set<Id> setId = new set<Id>();
            for(Policy__c poc : polList){
                setId.add(poc.opportunity_name__c);
            }
            integer i=0;
            list<Opportunity> fetchOpp = [Select id,policy_number__c,stagename from Opportunity where id in : setId];
             set<Id> setOppId = new set<Id>();
            for(Opportunity pcc: fetchOpp){
                setOppId.add(pcc.id);
            }
            list<Opportunity> updateOpp = new  list<Opportunity>();
            for(Policy__c pol : polList){
                for(Opportunity oldOpp : fetchOpp){
                     Opportunity OppDetails = new Opportunity();
              
                if(pol.policy_number__c == oldOpp.policy_number__c){
                    oldOpp.StageName = 'Closed Won';
                   
                    if(pol.parent_policy__c!=NuLL){
                    pol.Renew_Policy__c = True;
                    pol.opportunity_name__c = oldOpp.Id;
                   
                }
                     updateOpp.add(oldOpp);
               }
                
                } 
            }
            update updateOpp;
        }catch(Exception es){
            system.debug(es.getLineNumber());
           system.debug(es.getMessage());
           system.debug(es.getCause());
        }
        }
    }
}