force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/opportunity_name__c.field-meta.xml
<CustomField>
    <fullName>opportunity_name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>opportunity name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/policy_number__c.field-meta.xml
<CustomField>
    <fullName>policy_number__c</fullName>
    <label>policy number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Renew_Policy__c.field-meta.xml
<CustomField>
    <fullName>Renew_Policy__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Renew Policy</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PolicyTriggerUnitTest.cls
@isTest
 class PolicyTriggerUnitTest {

     @isTest
     static void TestPolicyTrigger(){
         Opportunity opp = new Opportunity(Name='KKr',StageName='Closed Won', CloseDate=date.today(),policy_number__c = 12445);
         insert opp;
         Policy__c pol = new Policy__c(Name='Policy',Renew_Policy__c=False,policy_number__c=12445,opportunity_name__c = opp.Id);
         insert pol;
         pol.Name='KKR';
         Test.startTest();
         update pol;
         Test.stopTest();
     }
}