force-app/main/default/objects/Bank__c/fields/BankAddress__c.field-meta.xml
<CustomField>
    <fullName>BankAddress__c</fullName>
    <label>BankAddress</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank__c/fields/IFSC__c.field-meta.xml
<CustomField>
    <fullName>IFSC__c</fullName>
    <label>IFSC</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <label>TotalAmount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bank__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BankInfoTest.cls
@isTest
private class BankInfoTest {

   
    static testmethod void bankfieldtest(){
        BankInfo.bankField();
    }
    

    static testmethod void saveBankDetailsTest(){
        
       Account acc = new Account(Name='xyz',Bank__c='SBI',BankAddress__c='Mirzapur',TotalAmount__c=1200,IFSC__c='SBI002B',Transaction__c='678' );
        test.startTest();
        BankInfo.saveBankDetails(acc);
        BankInfo.fetchBankDetails();
        test.stopTest();
    }
     
    static testmethod void transactioTest(){
          Account acc = new Account(Name='xyz',Bank__c='SBI',BankAddress__c='Mirzapur',TotalAmount__c=1200,IFSC__c='SBI002B',Transaction__c='678' );
      insert acc;
          test.startTest();
       BankInfo.trancation('100',acc.id,'Credit');
       BankInfo.trancation('50',acc.id,'Debit');
        test.stopTest();
    }
        
}