force-app/main/default/objects/Ca_User__c/Ca_User__c.object-meta.xml
<CustomObject>
    <label>CA User</label>
    <nameField>
        <label>Ca User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CaUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ca_User__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>IsActive</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ca_User__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>EmailId</description>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Ca_User__c/fields/Joining_Date__c.field-meta.xml
<CustomField>
    <fullName>Joining_Date__c</fullName>
    <description>JoiningDate</description>
    <label>Joining Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/AddCaUser.cls
public class AddCaUser {
    public static void addUser(){
      list<Ca_User__c> causr = new list<Ca_User__c>();
        causr = [Select id,Joining_Date__c from  Ca_User__c limit 1];
        for(integer i=0;i<50;i++){
       
          Ca_User__c ur = new Ca_User__c();
        ur.Email__c = 'abcd'+i+'@gmail.com'; 
            ur.Name = 'User'+i;
            if(causr[0].Joining_Date__c == system.today()){
                ur.Active__c = True;
            }
            else{
                ur.Active__c = False;        
       }
            insert ur;
    }
    }
}