force-app/main/default/objects/Ca_User__c/Ca_User__c.object-meta.xml
<CustomObject>
    <label>CA User</label>
    <nameField>
        <label>Ca User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CaUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ca_User__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>EmailId</description>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Ca_User__c/fields/Joining_Date__c.field-meta.xml
<CustomField>
    <fullName>Joining_Date__c</fullName>
    <description>JoiningDate</description>
    <label>Joining Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/AddCaUserUnitTest.cls
@isTest
private class AddCaUserUnitTest {

    @isTest 
   static void TestCaUser(){
        Ca_User__c causr = new Ca_User__c(name='This',  Joining_Date__c = date.today(),Email__c = 'abcd@gmail.com');
        insert causr;
        Test.startTest();
            AddCaUser.addUser();
        Test.stopTest();
    }
    
    @isTest
    static void TestNegative(){
         Ca_User__c causr = new Ca_User__c(name='This',  Joining_Date__c = date.today().addDays(1),Email__c = 'abcd@gmail.com');
        insert causr;
  Test.startTest();
            AddCaUser.addUser();
        Test.stopTest();
    }
}