force-app/main/default/objects/FileStore__c/FileStore__c.object-meta.xml
<CustomObject>
    <label>FileStore</label>
    <nameField>
        <label>FileStore Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FileStores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FileStore__c/fields/FileExtension__c.field-meta.xml
<CustomField>
    <fullName>FileExtension__c</fullName>
    <label>FileExtension</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FileStore__c/fields/S3ServerUrl__c.field-meta.xml
<CustomField>
    <fullName>S3ServerUrl__c</fullName>
    <label>S3ServerUrl</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

.history/force-app/main/default/classes/S3FileController_20220314182943.cls
public class S3FileController {
    @AuraEnabled
    public static string getFileUrl(string record)
    {
        try
        {
            List<FileStore__c> files=[SELECT  S3ServerUrl__c,FileExtension__c FROM FileStore__c 
                                      where Id=:record limit 1];
            FileStore__c file = files[0];
            return file.S3ServerUrl__c;
        }
        catch(Exception ex)
        {
            system.debug('ex:'+ex.getMessage());
            return '';
        }
    }
}