force-app/main/default/objects/EventParticipant__c/EventParticipant__c.object-meta.xml
<CustomObject>
    <description>Event Participant</description>
    <label>EventParticipant</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EventParticipants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EventParticipant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>EventParticipants</relationshipLabel>
    <relationshipName>EventParticipants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EventParticipant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>EventParticipants</relationshipLabel>
    <relationshipName>EventParticipants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CustomJunctionUnitTest.cls
@isTest
private class CustomJunctionUnitTest {
    @testSetup
    static void setupset() {
        Event__c ev = new Event__c(Name = 'Rummy Culture');
        insert ev;
        Contact con = new Contact(LastName = 'Singh');
        insert con;
        EventParticipant__c evp = new EventParticipant__c(Event__c=ev.id,Contact__c=con.Id,Name='hy');
        insert evp;
    }
    @isTest
    static void TestCustomJunction() {
        Test.startTest();
        CustomJunction.addJunctionObject();
        Test.stopTest();
        List<EventParticipant__c> sc = [Select id from EventParticipant__c];
        System.assertEquals(17, sc.Size());
    }
     
}