force-app/main/default/objects/EventParticipant__c/EventParticipant__c.object-meta.xml
<CustomObject>
    <description>Event Participant</description>
    <label>EventParticipant</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EventParticipants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EventParticipant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>EventParticipants</relationshipLabel>
    <relationshipName>EventParticipants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EventParticipant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>EventParticipants</relationshipLabel>
    <relationshipName>EventParticipants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EventParticipant__c/fields/multipicklist__c.field-meta.xml
<CustomField>
    <fullName>multipicklist__c</fullName>
    <label>multipicklist</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Attendee Contact</fullName>
            </value>
            <value>
                <fullName>Presenter Contact</fullName>
            </value>
            <value>
                <fullName>Organizer Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomJunction.cls
public class CustomJunction {
    public static void addJunctionObject(){
        list<EventParticipant__c> cstevent = new list<EventParticipant__c>();
        list<Contact> con = new list<Contact>([Select Id from Contact limit 1]);
        list<Event__c> eve = new list<Event__c>([Select Id from Event__c limit 1]);
        for(integer i=0;i<16;i++){
            EventParticipant__c addEvent = new EventParticipant__c();
            addEvent.Contact__c = con.get(0).Id;
            addEvent.Event__c = eve.get(0).Id;
            if(i>=0 && i<=10){   
                addEvent.multipicklist__c = 'Attendee';
                addEvent.Name = 'EventFootball'+i;
                
            }
            if(i>=11 && i<14){
                
                addEvent.multipicklist__c = 'Presenter';
                addEvent.Name = 'EventjunFootball'+i+i;
            }
            if(i>=14 && i<17)
            {
                addEvent.multipicklist__c = 'Organizer';
                addEvent.Name = 'EventjunFootball'+i+i+i; 
            }
            cstevent.add(addEvent);
        }if(cstevent!=Null){
            insert cstevent;
            system.debug(cstevent.size());
        }
        
    }
}