force-app/main/default/objects/Region__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <label>AccountId</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/School__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <label>AccountId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/School.cls
public class School {   
    public static void school(){
list<Region__c> rg=new list<Region__c>();
   rg=[select Id from Region__c limit 5];
        list<School__c> sl = new  list<School__c>();
        integer i=0;
        for(Region__c ac:rg){
            School__c sch = new School__c();
            sch.Name = 'School'+i;
            i++;
            sch.AccountId__c = ac.Id;
            sl.add(sch);
        }
    insert sl;
        System.debug('School Records : '+sl);
}
}