force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <description>Travelling hour</description>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/travellHour__c.field-meta.xml
<CustomField>
    <fullName>travellHour__c</fullName>
    <description>Tavell Hour</description>
    <label>travelHour</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/travelLocation__c.field-meta.xml
<CustomField>
    <fullName>travelLocation__c</fullName>
    <label>travelLocation</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Travellers_Test.cls
@isTest
private class Travellers_Test {
    
    @TestSetup
    static void setupData(){
        Plan__c addPlan = new Plan__c();
        addPlan.Name = 'Ranchi';
        addPlan.travellHour__c = 5 ;
        addPlan.travelLocation__c = 'A' ;
        insert addPlan;
    }
    @isTest
    static void TestTravellers(){
        Test.startTest();
        Travellers.travllr();
        Test.stopTest();
        system.assertEquals(1, 1);
    }
    
}