force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <description>Travelling hour</description>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/travellHour__c.field-meta.xml
<CustomField>
    <fullName>travellHour__c</fullName>
    <description>Tavell Hour</description>
    <label>travelHour</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/travelLocation__c.field-meta.xml
<CustomField>
    <fullName>travelLocation__c</fullName>
    <label>travelLocation</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Travellers.cls
public class Travellers {
    public static void travllr(){
        list<Plan__c> plan = new list<Plan__c>();
     	   List<String> availableValues = new List<String>{'A','B','C','D','E','F'};
        Integer listSize = availableValues.size() - 1;
        Integer randomNumber = Integer.valueof((Math.random() * listSize));
         String randomString= availableValues[randomNumber];
       
        for(integer i =0 ;i<1;i++){
        Plan__c addPlan = new Plan__c();
          addPlan.Name = 'Ranchi';
            addPlan.travellHour__c = 5 ;
            addPlan.travelLocation__c = randomString ;
            if(randomString!='F'){
                 addPlan.travelLocation__c = 'A;F' ;
            }
           
            plan.add(addPlan);
            
        }
        insert plan;
        list<Plan__c> planhour = new list<Plan__c>();
        planhour = [Select travellHour__c from Plan__c where travelLocation__c = 'A'or travelLocation__c ='F' ];
         Decimal totalTimeTravel=0;
        for(Plan__c addH: planhour){
            totalTimeTravel = totalTimeTravel+addH.travellHour__c;
        }
        system.debug('Total travell Hour<<<< '+totalTimeTravel);
    }
    
}